name: Windows CI

on: 
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build-and-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Show tool versions
        run: |
          cmake --version
          ctest --version
          cl
        shell: cmd

      - name: Configure
        run: cmake --preset x64-debug-ddknd-tests

      - name: build
        run: cmake --build --preset x64-debug-ddknd-tests

      - name: Run tests
        run: ctest --preset x64-debug-ddknd-tests --output-on-failure

